# Generated by Django 4.1.2 on 2023-05-23 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='defult/defult.jpg', null=True, upload_to='Profpic/'),
        ),
    ]
